// client/src/pages/Contact.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { MapPinIcon, PhoneIcon, MailIcon, ClockIcon, ExternalLinkIcon, SendIcon, LoaderCircleIcon } from 'lucide-vue-next';
import Button from '@/components/ui/Button.vue';
import Input from '@/components/ui/Input.vue';
import Textarea from '@/components/ui/Textarea.vue';
import Select, { type SelectItem } from '@/components/ui/Select.vue';
import { useContactStore } from '@/store/contactStore';
// Import Zod and schema for frontend validation if desired
// import { z } from 'zod';
// import { extendedContactSchema } from '../../../shared/schema'; // Adjust path as needed

// import mapPlaceholderPath from '@/assets/images/map-placeholder.png'; // Commented out - file likely missing
const mapPlaceholderPath = ''; // Placeholder

// Form field refs - these will constitute the ContactFormData
const name = ref('');
const email = ref('');
const phone = ref(''); // Optional in schema, so can be empty string or undefined
const subject = ref(''); // This is 'bookingType' in the old formData
const message = ref('');

// Additional fields from old formData, to be included in the message or handled differently
const partySize = ref<number | null>(null);
const bookingDate = ref('');
const bookingTime = ref('');
const howHeard = ref('');

const contactStore = useContactStore();

const todayDate = computed(() => {
  const today = new Date();
  return today.toISOString().split('T')[0];
});

// These correspond to the 'subject' field in the shared schema (InsertContact)
// which was 'bookingType' in the old local form data.
const subjectOptions: SelectItem[] = [
  { label: 'General Inquiry', value: 'inquiry' },
  { label: 'Table Reservation', value: 'reservation' },
  { label: 'Event Booking', value: 'event' },
  { label: 'Feedback', value: 'feedback' },
];

const howHeardOptions: SelectItem[] = [
  { label: 'Select an option', value: '' },
  { label: 'Friends/Family', value: 'friends_family' },
  { label: 'Online Search (Google, etc.)', value: 'online_search' },
  { label: 'Social Media', value: 'social_media' },
  { label: 'Local Event/Advertisement', value: 'local_event' },
  { label: 'Returning Customer', value: 'returning_customer' },
  { label: 'Other', value: 'other' },
];

async function handleSubmit() {
  let finalMessage = message.value;
  // Append booking details to the message if a reservation or event
  if (subject.value === 'reservation' || subject.value === 'event') {
    finalMessage += `\n\n--- Booking Details ---`;
    if (partySize.value) finalMessage += `\nParty Size: ${partySize.value}`;
    if (bookingDate.value) finalMessage += `\nDate: ${bookingDate.value}`;
    if (bookingTime.value) finalMessage += `\nTime: ${bookingTime.value}`;
  }
  if (howHeard.value) {
     finalMessage += `\nHow heard: ${howHeard.value}`;
  }


  const formDataForStore = {
    name: name.value,
    email: email.value,
    phone: phone.value || undefined, // Send undefined if empty, as per schema for optional
    subject: subject.value, // This is the 'bookingType' equivalent
    message: finalMessage,
  };

  // Optional: Frontend validation using Zod (uncomment and adjust schema import if needed)
  // const validationResult = extendedContactSchema.safeParse(formDataForStore);
  // if (!validationResult.success) {
  //   const firstError = validationResult.error.errors[0];
  //   contactStore.toast({ // Assuming toast is accessible or part of store for consistency
  //     title: 'Validation Error',
  //     description: `${firstError.path.join('.')} - ${firstError.message}`,
  //     variant: 'destructive',
  //   });
  //   return;
  // }
  // const dataToSubmit = validationResult.data; // Use validated data

  const success = await contactStore.submitContactForm(formDataForStore); // Use formDataForStore or dataToSubmit if validation is active
  
  if (success) {
    name.value = '';
    email.value = '';
    phone.value = '';
    subject.value = 'inquiry'; // Reset to default
    message.value = '';
    partySize.value = null;
    bookingDate.value = '';
    bookingTime.value = '';
    howHeard.value = '';
  }
}
</script>

<template>
  <div class="bg-gray-50 text-gray-800">
    <!-- Page Header Section -->
    <section class="bg-yellow-500 text-green-900 py-12 md:py-20">
      <div class="container mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <h1 class="font-heading text-4xl md:text-5xl font-bold">Contact Us</h1>
        <p class="text-lg md:text-xl text-green-800 mt-4 max-w-2xl mx-auto">
          We'd love to hear from you! Whether it's for reservations, inquiries, or feedback.
        </p>
      </div>
    </section>

    <!-- Contact Information & Map Section -->
    <section class="py-16 md:py-24 bg-white">
      <div class="container mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid md:grid-cols-2 gap-12 items-start">
          <!-- Contact Details -->
          <div>
            <h2 class="font-heading text-3xl md:text-4xl font-semibold text-green-800 mb-8">
              Get in Touch
            </h2>
            <div class="space-y-6">
              <div class="flex items-start">
                <MapPinIcon class="h-7 w-7 text-yellow-500 mr-4 mt-1 flex-shrink-0" />
                <div>
                  <h3 class="text-xl font-semibold text-green-700">Our Address</h3>
                  <p class="text-gray-600">123 Addis Ababa Street, Flavor Town, ET 90210</p>
                  <a href="https://maps.google.com/?q=123+Addis+Ababa+Street,+Flavor+Town,+ET+90210" target="_blank" rel="noopener noreferrer" class="text-yellow-600 hover:text-yellow-700 font-medium inline-flex items-center mt-1">
                    Get Directions <ExternalLinkIcon class="h-4 w-4 ml-1.5" />
                  </a>
                </div>
              </div>
              <div class="flex items-start">
                <PhoneIcon class="h-7 w-7 text-yellow-500 mr-4 mt-1 flex-shrink-0" />
                <div>
                  <h3 class="text-xl font-semibold text-green-700">Call Us</h3>
                  <p class="text-gray-600">Reservations & Inquiries: <a href="tel:+251912345678" class="text-yellow-600 hover:text-yellow-700">+251 912 345 678</a></p>
                </div>
              </div>
              <div class="flex items-start">
                <MailIcon class="h-7 w-7 text-yellow-500 mr-4 mt-1 flex-shrink-0" />
                <div>
                  <h3 class="text-xl font-semibold text-green-700">Email Us</h3>
                  <p class="text-gray-600">General: <a href="mailto:info@harambe.com" class="text-yellow-600 hover:text-yellow-700">info@harambe.com</a></p>
                  <p class="text-gray-600">Events: <a href="mailto:events@harambe.com" class="text-yellow-600 hover:text-yellow-700">events@harambe.com</a></p>
                </div>
              </div>
              <div class="flex items-start">
                <ClockIcon class="h-7 w-7 text-yellow-500 mr-4 mt-1 flex-shrink-0" />
                <div>
                  <h3 class="text-xl font-semibold text-green-700">Opening Hours</h3>
                  <p class="text-gray-600">Monday - Friday: 11:00 AM - 10:00 PM</p>
                  <p class="text-gray-600">Saturday - Sunday: 10:00 AM - 11:00 PM</p>
                </div>
              </div>
            </div>
          </div>

          <!-- Map Placeholder -->
          <div class="rounded-lg overflow-hidden shadow-xl h-96 md:h-full">
            <img :src="mapPlaceholderPath" alt="Map showing restaurant location" class="w-full h-full object-cover" />
            <!-- In a real app, this would be an interactive map component -->
          </div>
        </div>
      </div>
    </section>

    <!-- Contact Form Section -->
    <section id="booking-form" class="py-16 md:py-24 bg-green-50 scroll-mt-20">
      <div class="container mx-auto px-4 sm:px-6 lg:px-8">
        <div class="max-w-3xl mx-auto">
          <h2 class="font-heading text-3xl md:text-4xl font-semibold text-green-800 text-center mb-10">
            Send Us a Message or Book a Table
          </h2>
          <form @submit.prevent="handleSubmit" class="bg-white p-8 md:p-10 rounded-xl shadow-2xl space-y-6">
            <div class="grid sm:grid-cols-2 gap-6">
              <div>
                <label for="name" class="block text-sm font-medium text-gray-700 mb-1.5">Full Name</label>
                <Input
                  type="text"
                  id="name"
                  v-model="name"
                  required
                  placeholder="e.g. John Doe"
                />
              </div>
              <div>
                <label for="email" class="block text-sm font-medium text-gray-700 mb-1.5">Email Address</label>
                <Input
                  type="email"
                  id="email"
                  v-model="email"
                  required
                  placeholder="you@example.com"
                />
              </div>
            </div>

            <div>
              <label for="phone" class="block text-sm font-medium text-gray-700 mb-1.5">Phone Number <span class="text-xs text-gray-500">(Optional)</span></label>
              <Input
                type="tel"
                id="phone"
                v-model="phone"
                placeholder="+1 (555) 123-4567"
              />
            </div>

            <div>
              <label for="subject" class="block text-sm font-medium text-gray-700 mb-1.5">Subject / Type</label>
               <Select
                  id="subject"
                  v-model="subject"
                  :items="subjectOptions"
                  placeholder="Select a subject"
                />
            </div>
            
            <!-- Conditional fields for reservation/event -->
            <template v-if="subject === 'reservation' || subject === 'event'">
              <div class="grid sm:grid-cols-2 gap-6">
                <div>
                    <label for="partySize" class="block text-sm font-medium text-gray-700 mb-1.5">Number of Guests</label>
                    <Input
                      type="number"
                      id="partySize"
                      v-model.number="partySize"
                      min="1"
                      placeholder="e.g. 4"
                    />
                </div>
                 <div>
                    <label for="bookingDate" class="block text-sm font-medium text-gray-700 mb-1.5">Preferred Date</label>
                    <Input
                        type="date"
                        id="bookingDate"
                        v-model="bookingDate"
                        :min="todayDate"
                    />
                </div>
              </div>
              <div>
                  <label for="bookingTime" class="block text-sm font-medium text-gray-700 mb-1.5">Preferred Time</label>
                  <Input
                      type="time"
                      id="bookingTime"
                      v-model="bookingTime"
                  />
              </div>
            </template>

            <div>
              <label for="message" class="block text-sm font-medium text-gray-700 mb-1.5">Message</label>
              <Textarea
                id="message"
                v-model="message"
                required
                rows="5"
                placeholder="Write your message or additional booking details here..."
              />
            </div>

            <div>
              <label for="howHeard" class="block text-sm font-medium text-gray-700 mb-1.5">How did you hear about us? <span class="text-xs text-gray-500">(Optional)</span></label>
              <Select
                id="howHeard"
                v-model="howHeard"
                :items="howHeardOptions"
                placeholder="Select an option"
              />
            </div>
            
            <p v-if="contactStore.error" class="text-sm text-red-600 mt-2 text-center">{{ contactStore.error }}</p>

            <div class="pt-4">
              <Button
                type="submit"
                class="w-full text-lg"
                variant="default"
                size="lg"
                :disabled="contactStore.isLoading"
              >
                <SendIcon v-if="!contactStore.isLoading" class="h-5 w-5 mr-2.5" />
                <LoaderCircleIcon v-if="contactStore.isLoading" class="h-5 w-5 mr-2.5 animate-spin" />
                {{ contactStore.isLoading ? 'Sending...' : 'Send Message / Book Table' }}
              </Button>
            </div>
          </form>
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
.font-heading {
  font-family: 'Nyala', serif; /* Ensure this font is configured */
}
/* Styles for native date/time input placeholder text (if needed and supported) */
input[type="date"]:not(:valid):before,
input[type="time"]:not(:valid):before {
  content: attr(placeholder);
  color: #9ca3af; /* Tailwind gray-400 */
}
</style>

// client/src/pages/Contact.tsx
import { useState } from "react";
import { z } from "zod";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import { extendedContactSchema } from "@shared/schema";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { MapPin, Phone, Mail, Clock } from "lucide-react";

type FormValues = z.infer<typeof extendedContactSchema>;

export default function Contact() {
  const { toast } = useToast();
  
  const form = useForm<FormValues>({
    resolver: zodResolver(extendedContactSchema),
    defaultValues: {
      name: "",
      email: "",
      phone: "",
      subject: "",
      message: "",
    },
  });
  
  const { mutate, isPending } = useMutation({
    mutationFn: async (data: FormValues) => {
      const response = await apiRequest("POST", "/api/contact", data);
      return response.json();
    },
    onSuccess: (data) => {
      toast({
        title: "Success!",
        description: data.message || "Thank you for your message! We will get back to you soon.",
      });
      form.reset();
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to submit the form. Please try again.",
        variant: "destructive",
      });
    },
  });

  const onSubmit = (data: FormValues) => {
    mutate(data);
  };

  return (
    <section className="py-16 md:py-24 bg-[hsl(44,100%,95%)]">
      <div className="container mx-auto">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <span className="font-accent text-xl text-[hsl(44,100%,52%)]">Get In Touch</span>
          <h2 className="font-heading text-3xl md:text-4xl font-bold text-primary mt-2 mb-6">Contact Us</h2>
          <p className="text-[#757575]">We'd love to hear from you! Reach out for reservations, feedback, or special event inquiries.</p>
          <div className="w-20 h-1 bg-primary mx-auto mt-6"></div>
        </div>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* Contact Form */}
          <div className="bg-white p-8 rounded-lg shadow-md">
            <h3 className="font-heading text-2xl font-semibold mb-6 text-primary">Send Us a Message</h3>
            
            <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                <FormField
                  control={form.control}
                  name="name"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Name</FormLabel>
                      <FormControl>
                        <Input placeholder="Your Name" {...field} className="focus-visible:ring-primary" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                
                <FormField
                  control={form.control}
                  name="email"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Email</FormLabel>
                      <FormControl>
                        <Input placeholder="your.email@example.com" type="email" {...field} className="focus-visible:ring-primary" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                
                <FormField
                  control={form.control}
                  name="phone"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Phone</FormLabel>
                      <FormControl>
                        <Input placeholder="(123) 456-7890" type="tel" {...field} className="focus-visible:ring-primary" />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                
                <FormField
                  control={form.control}
                  name="subject"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Subject</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger className="focus-visible:ring-primary">
                            <SelectValue placeholder="Please select a subject" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="reservation">Reservation</SelectItem>
                          <SelectItem value="feedback">Feedback</SelectItem>
                          <SelectItem value="event">Private Event</SelectItem>
                          <SelectItem value="other">Other</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                
                <FormField
                  control={form.control}
                  name="message"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Message</FormLabel>
                      <FormControl>
                        <Textarea 
                          placeholder="How can we help you?" 
                          className="resize-none focus-visible:ring-primary" 
                          rows={4} 
                          {...field} 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                
                <Button 
                  type="submit" 
                  className="w-full bg-[hsl(0,64%,50%)] hover:bg-[hsl(0,64%,45%)]"
                  disabled={isPending}
                >
                  {isPending ? "Sending..." : "Send Message"}
                </Button>
              </form>
            </Form>
          </div>
          
          {/* Contact Information */}
          <div>
            <h3 className="font-heading text-2xl font-semibold mb-6 text-primary">Visit Us</h3>
            
            <div className="mb-8">
              <div className="flex items-start mb-4">
                <MapPin className="text-[hsl(44,100%,52%)] h-5 w-5 mr-4 mt-1" />
                <div>
                  <h4 className="font-medium">Address</h4>
                  <p className="text-[#757575]">123 Green Street, Culinary District<br/>Your City, ST 12345</p>
                </div>
              </div>
              
              <div className="flex items-start mb-4">
                <Phone className="text-[hsl(44,100%,52%)] h-5 w-5 mr-4 mt-1" />
                <div>
                  <h4 className="font-medium">Phone</h4>
                  <p className="text-[#757575]">(123) 456-7890</p>
                </div>
              </div>
              
              <div className="flex items-start mb-4">
                <Mail className="text-[hsl(44,100%,52%)] h-5 w-5 mr-4 mt-1" />
                <div>
                  <h4 className="font-medium">Email</h4>
                  <p className="text-[#757575]">info@verdanttable.com</p>
                </div>
              </div>
              
              <div className="flex items-start">
                <Clock className="text-[hsl(44,100%,52%)] h-5 w-5 mr-4 mt-1" />
                <div>
                  <h4 className="font-medium">Hours</h4>
                  <p className="text-[#757575]">
                    Monday - Friday: 11:00 AM - 10:00 PM<br/>
                    Saturday & Sunday: 10:00 AM - 11:00 PM
                  </p>
                </div>
              </div>
            </div>
            
            {/* Map */}
            <div className="w-full h-64 bg-gray-200 rounded-lg overflow-hidden relative">
              <iframe 
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3024.2219901290355!2d-74.00369368400567!3d40.71312937933185!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a23e28c1191%3A0x49f75d3281df052a!2s123%20Street%2C%20New%20York%2C%20NY%2010001%2C%20USA!5e0!3m2!1sen!2sus!4v1616593073367!5m2!1sen!2sus" 
                width="100%" 
                height="100%" 
                style={{ border: 0 }} 
                allowFullScreen 
                loading="lazy"
                referrerPolicy="no-referrer-when-downgrade"
                title="Restaurant location"
              ></iframe>
              
              {/* Map overlay with restaurant location pin */}
              <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center pointer-events-none">
                <div className="bg-primary text-white px-3 py-2 rounded-lg shadow-lg">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 inline-block mr-2" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                  Verdant Table
                </div>
              </div>
            </div>
            
            {/* Social Media */}
            <div className="mt-8">
              <h4 className="font-medium mb-4">Follow Us</h4>
              <div className="flex space-x-4">
                <a href="#" className="text-primary hover:text-[hsl(122,63%,25%)] transition-colors">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" viewBox="0 0 24 24" fill="currentColor"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"/></svg>
                </a>
                <a href="#" className="text-primary hover:text-[hsl(122,63%,25%)] transition-colors">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/></svg>
                </a>
                <a href="#" className="text-primary hover:text-[hsl(122,63%,25%)] transition-colors">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" viewBox="0 0 24 24" fill="currentColor"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/></svg>
                </a>
                <a href="#" className="text-primary hover:text-[hsl(122,63%,25%)] transition-colors">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm4.326 18.266l-4.326-2.314-4.326 2.313.863-4.829-3.537-3.399 4.86-.671 2.14-4.415 2.14 4.415 4.86.671-3.537 3.4.863 4.829z"/></svg>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
