// client/src/pages/Menu.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { menuData } from "@/data/menuData";
import { Star } from "lucide-react";

type Category = "all" | "appetizers" | "vegetarian" | "beef" | "chicken" | "lamb" | "combination-platters" | "fish" | "injera";

export default function Menu() {
  const [activeCategory, setActiveCategory] = useState<Category>("all");
  
  // Filter menu items based on active category
  const filteredItems = activeCategory === "all" 
    ? [...menuData.appetizers, ...menuData.vegetarian, ...menuData.beef, ...menuData.chicken, ...menuData.lamb, ...menuData.combinationPlatters, ...menuData.fish, ...menuData.injera] 
    : menuData[activeCategory === "combination-platters" ? "combinationPlatters" : activeCategory as keyof typeof menuData] || [];

  return (
    <section className="py-16 md:py-24 bg-[hsl(44,100%,95%)]">
      <div className="container mx-auto">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <span className="font-accent text-xl text-[hsl(44,100%,52%)]">Seasonal & Fresh</span>
          <h2 className="font-heading text-3xl md:text-4xl font-bold text-primary mt-2 mb-6">Our Menu</h2>
          <p className="text-[#757575]">Our menu changes with the seasons to bring you the freshest, most flavorful dishes year-round.</p>
          <div className="w-20 h-1 bg-primary mx-auto mt-6"></div>
        </div>
        
        {/* Menu Categories */}
        <div className="flex flex-wrap justify-center gap-4 mb-12">
          <Button 
            variant={activeCategory === "all" ? "default" : "outline"} 
            onClick={() => setActiveCategory("all")}
            className={activeCategory === "all" ? "bg-primary text-white" : "text-primary border-primary"}
          >
            All
          </Button>
          <Button 
            variant={activeCategory === "appetizers" ? "default" : "outline"} 
            onClick={() => setActiveCategory("appetizers")}
            className={activeCategory === "appetizers" ? "bg-primary text-white" : "text-primary border-primary"}
          >
            Appetizers
          </Button>
          <Button 
            variant={activeCategory === "vegetarian" ? "default" : "outline"} 
            onClick={() => setActiveCategory("vegetarian")}
            className={activeCategory === "vegetarian" ? "bg-primary text-white" : "text-primary border-primary"}
          >
            Vegetarian
          </Button>
          <Button 
            variant={activeCategory === "beef" ? "default" : "outline"} 
            onClick={() => setActiveCategory("beef")}
            className={activeCategory === "beef" ? "bg-primary text-white" : "text-primary border-primary"}
          >
            Beef
          </Button>
          <Button 
            variant={activeCategory === "chicken" ? "default" : "outline"} 
            onClick={() => setActiveCategory("chicken")}
            className={activeCategory === "chicken" ? "bg-primary text-white" : "text-primary border-primary"}
          >
            Chicken
          </Button>
          <Button 
            variant={activeCategory === "lamb" ? "default" : "outline"} 
            onClick={() => setActiveCategory("lamb")}
            className={activeCategory === "lamb" ? "bg-primary text-white" : "text-primary border-primary"}
          >
            Lamb
          </Button>
          <Button 
            variant={activeCategory === "combination-platters" ? "default" : "outline"} 
            onClick={() => setActiveCategory("combination-platters")}
            className={activeCategory === "combination-platters" ? "bg-primary text-white" : "text-primary border-primary"}
          >
            Combination Platters
          </Button>
          <Button 
            variant={activeCategory === "fish" ? "default" : "outline"} 
            onClick={() => setActiveCategory("fish")}
            className={activeCategory === "fish" ? "bg-primary text-white" : "text-primary border-primary"}
          >
            Fish
          </Button>
          <Button 
            variant={activeCategory === "injera" ? "default" : "outline"} 
            onClick={() => setActiveCategory("injera")}
            className={activeCategory === "injera" ? "bg-primary text-white" : "text-primary border-primary"}
          >
            Injera
          </Button>
        </div>
        
        {/* Appetizers Section */}
        {(activeCategory === "all" || activeCategory === "appetizers") && (
          <div className="menu-section mb-16">
            <h3 className="font-heading text-2xl font-semibold mb-8 text-primary">Appetizers</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {menuData.appetizers && menuData.appetizers.map((item) => (
                <div key={item.id} className="flex gap-4">
                  <img 
                    src={item.image} 
                    alt={item.name} 
                    className="w-24 h-24 rounded-md object-cover"
                  />
                  <div className="flex-1">
                    <div className="flex justify-between items-start">
                      <h4 className="font-heading font-medium text-lg">{item.name}</h4>
                      <span className="text-[hsl(0,64%,50%)] font-medium">${item.price}</span>
                    </div>
                    <p className="text-[#757575] text-sm mt-1">{item.description}</p>
                    {item.dietary && (
                      <Badge variant="secondary" className="mt-2 bg-[hsl(44,100%,52%)]/20 text-[hsl(122,63%,25%)] hover:bg-[hsl(44,100%,52%)]/30">
                        {item.dietary}
                      </Badge>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Vegetarian Section */}
        {(activeCategory === "all" || activeCategory === "vegetarian") && (
          <div className="menu-section mb-16">
            <h3 className="font-heading text-2xl font-semibold mb-8 text-primary">Vegetarian</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {menuData.vegetarian && menuData.vegetarian.map((item) => (
                <div key={item.id} className="flex gap-4">
                  <img 
                    src={item.image} 
                    alt={item.name} 
                    className="w-24 h-24 rounded-md object-cover"
                  />
                  <div className="flex-1">
                    <div className="flex justify-between items-start">
                      <h4 className="font-heading font-medium text-lg">{item.name}</h4>
                      <span className="text-[hsl(0,64%,50%)] font-medium">${item.price}</span>
                    </div>
                    <p className="text-[#757575] text-sm mt-1">{item.description}</p>
                    {item.dietary && (
                      <Badge variant="secondary" className="mt-2 bg-[hsl(44,100%,52%)]/20 text-[hsl(122,63%,25%)] hover:bg-[hsl(44,100%,52%)]/30">
                        {item.dietary}
                      </Badge>
                    )}
                    {item.popular && (
                      <div className="mt-2">
                        <span className="text-[hsl(44,100%,52%)] flex">
                          {[...Array(5)].map((_, i) => (
                            <Star key={i} className="h-4 w-4 fill-current" />
                          ))}
                          <span className="text-xs text-[#757575] ml-1">Popular</span>
                        </span>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Beef Section */}
        {(activeCategory === "all" || activeCategory === "beef") && (
          <div className="menu-section mb-16">
            <h3 className="font-heading text-2xl font-semibold mb-8 text-primary">Beef</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {menuData.beef && menuData.beef.map((item) => (
                <div key={item.id} className="flex gap-4">
                  <img 
                    src={item.image} 
                    alt={item.name} 
                    className="w-24 h-24 rounded-md object-cover"
                  />
                  <div className="flex-1">
                    <div className="flex justify-between items-start">
                      <h4 className="font-heading font-medium text-lg">{item.name}</h4>
                      <span className="text-[hsl(0,64%,50%)] font-medium">${item.price}</span>
                    </div>
                    <p className="text-[#757575] text-sm mt-1">{item.description}</p>
                    {item.dietary && (
                      <Badge variant="secondary" className="mt-2 bg-[hsl(44,100%,52%)]/20 text-[hsl(122,63%,25%)] hover:bg-[hsl(44,100%,52%)]/30">
                        {item.dietary}
                      </Badge>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Chicken Section */}
        {(activeCategory === "all" || activeCategory === "chicken") && (
          <div className="menu-section mb-16">
            <h3 className="font-heading text-2xl font-semibold mb-8 text-primary">Chicken</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {menuData.chicken && menuData.chicken.map((item) => (
                <div key={item.id} className="flex gap-4">
                  <img 
                    src={item.image} 
                    alt={item.name} 
                    className="w-24 h-24 rounded-md object-cover"
                  />
                  <div className="flex-1">
                    <div className="flex justify-between items-start">
                      <h4 className="font-heading font-medium text-lg">{item.name}</h4>
                      <span className="text-[hsl(0,64%,50%)] font-medium">${item.price}</span>
                    </div>
                    <p className="text-[#757575] text-sm mt-1">{item.description}</p>
                    {item.dietary && (
                      <Badge variant="secondary" className="mt-2 bg-[hsl(44,100%,52%)]/20 text-[hsl(122,63%,25%)] hover:bg-[hsl(44,100%,52%)]/30">
                        {item.dietary}
                      </Badge>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Lamb Section */}
        {(activeCategory === "all" || activeCategory === "lamb") && (
          <div className="menu-section mb-16">
            <h3 className="font-heading text-2xl font-semibold mb-8 text-primary">Lamb</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {menuData.lamb && menuData.lamb.map((item) => (
                <div key={item.id} className="flex gap-4">
                  <img 
                    src={item.image} 
                    alt={item.name} 
                    className="w-24 h-24 rounded-md object-cover"
                  />
                  <div className="flex-1">
                    <div className="flex justify-between items-start">
                      <h4 className="font-heading font-medium text-lg">{item.name}</h4>
                      <span className="text-[hsl(0,64%,50%)] font-medium">${item.price}</span>
                    </div>
                    <p className="text-[#757575] text-sm mt-1">{item.description}</p>
                    {item.dietary && (
                      <Badge variant="secondary" className="mt-2 bg-[hsl(44,100%,52%)]/20 text-[hsl(122,63%,25%)] hover:bg-[hsl(44,100%,52%)]/30">
                        {item.dietary}
                      </Badge>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Combination Platters Section */}
        {(activeCategory === "all" || activeCategory === "combination-platters") && (
          <div className="menu-section mb-16">
            <h3 className="font-heading text-2xl font-semibold mb-8 text-primary">Combination Platters</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {menuData.combinationPlatters && menuData.combinationPlatters.map((item) => (
                <div key={item.id} className="flex gap-4">
                  <img 
                    src={item.image} 
                    alt={item.name} 
                    className="w-24 h-24 rounded-md object-cover"
                  />
                  <div className="flex-1">
                    <div className="flex justify-between items-start">
                      <h4 className="font-heading font-medium text-lg">{item.name}</h4>
                      <span className="text-[hsl(0,64%,50%)] font-medium">
                        {typeof item.price === 'object' ? 
                          Object.entries(item.price).map(([key, value], index) => (
                            <div key={index}>{key}: ${value}</div>
                          )) : 
                          `$${item.price}`
                        }
                      </span>
                    </div>
                    <p className="text-[#757575] text-sm mt-1">{item.description}</p>
                    {item.dietary && (
                      <Badge variant="secondary" className="mt-2 bg-[hsl(44,100%,52%)]/20 text-[hsl(122,63%,25%)] hover:bg-[hsl(44,100%,52%)]/30">
                        {item.dietary}
                      </Badge>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Fish Section */}
        {(activeCategory === "all" || activeCategory === "fish") && (
          <div className="menu-section mb-16">
            <h3 className="font-heading text-2xl font-semibold mb-8 text-primary">Fish</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {menuData.fish && menuData.fish.map((item) => (
                <div key={item.id} className="flex gap-4">
                  <img 
                    src={item.image} 
                    alt={item.name} 
                    className="w-24 h-24 rounded-md object-cover"
                  />
                  <div className="flex-1">
                    <div className="flex justify-between items-start">
                      <h4 className="font-heading font-medium text-lg">{item.name}</h4>
                      <span className="text-[hsl(0,64%,50%)] font-medium">${item.price}</span>
                    </div>
                    <p className="text-[#757575] text-sm mt-1">{item.description}</p>
                    {item.dietary && (
                      <Badge variant="secondary" className="mt-2 bg-[hsl(44,100%,52%)]/20 text-[hsl(122,63%,25%)] hover:bg-[hsl(44,100%,52%)]/30">
                        {item.dietary}
                      </Badge>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Injera Section */}
        {(activeCategory === "all" || activeCategory === "injera") && (
          <div className="menu-section mb-16">
            <h3 className="font-heading text-2xl font-semibold mb-8 text-primary">Injera</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {menuData.injera && menuData.injera.map((item) => (
                <div key={item.id} className="flex gap-4">
                  <img 
                    src={item.image} 
                    alt={item.name} 
                    className="w-24 h-24 rounded-md object-cover"
                  />
                  <div className="flex-1">
                    <div className="flex justify-between items-start">
                      <h4 className="font-heading font-medium text-lg">{item.name}</h4>
                      <span className="text-[hsl(0,64%,50%)] font-medium">{item.price ? `$${item.price}` : ''}</span>
                    </div>
                    <p className="text-[#757575] text-sm mt-1">{item.description}</p>
                    {item.dietary && (
                      <Badge variant="secondary" className="mt-2 bg-[hsl(44,100%,52%)]/20 text-[hsl(122,63%,25%)] hover:bg-[hsl(44,100%,52%)]/30">
                        {item.dietary}
                      </Badge>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        
        <div className="text-center mt-16">
          <p className="text-[#757575] italic mb-4">* Menu items may contain allergens. Please inform your server of any dietary restrictions.</p>
          <Button className="bg-primary hover:bg-primary/90">
            Download Full Menu
          </Button>
        </div>
      </div>
    </section>
  );
}

// client/src/pages/Menu.vue
<template>
  <div class="bg-gray-50 text-gray-800">
    <!-- Page Header Section -->
    <section class="bg-yellow-500 text-green-900 py-12 md:py-20">
      <div class="container mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <h1 class="font-heading text-4xl md:text-5xl font-bold">Our Menu</h1>
        <p class="text-lg md:text-xl text-green-800 mt-4 max-w-2xl mx-auto">
          Explore a wide variety of authentic Ethiopian dishes, from savory wots to fresh injera.
        </p>
      </div>
    </section>

    <!-- Menu Section -->
    <section class="py-16 md:py-24">
      <div class="container mx-auto px-4 sm:px-6 lg:px-8">
        <!-- Category Filters -->
        <div class="mb-12 flex flex-wrap justify-center gap-3">
          <Button
            @click="setActiveCategory('all')"
            :variant="activeCategory === 'all' ? 'default' : 'outline'"
            class="px-6 py-3 text-sm md:text-base"
            :class="{'bg-green-700 hover:bg-green-800 text-white shadow-lg': activeCategory === 'all', 'bg-white text-green-700 border border-green-200 hover:bg-green-50 hover:shadow-md': activeCategory !== 'all'}"
          >
            All Dishes
          </Button>
          <Button
            v-for="category in uniqueCategories"
            :key="category.id"
            @click="setActiveCategory(category.id)"
            :variant="activeCategory === category.id ? 'default' : 'outline'"
            class="px-6 py-3 text-sm md:text-base"
            :class="{'bg-green-700 hover:bg-green-800 text-white shadow-lg': activeCategory === category.id, 'bg-white text-green-700 border border-green-200 hover:bg-green-50 hover:shadow-md': activeCategory !== category.id}"
          >
            {{ category.name }}
          </Button>
        </div>

        <!-- Menu Grid -->
        <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-12">
          <div
            v-for="item in filteredItems"
            :key="item.id"
            class="bg-white rounded-xl shadow-lg overflow-hidden transition-transform transform hover:scale-105 duration-300 flex flex-col"
          >
            <div class="relative">
              <img :src="item.image" :alt="item.name" class="w-full h-64 object-cover">
              <Badge
                v-if="item.isSpecial"
                variant="default"
                class="absolute top-3 right-3 bg-yellow-400 text-green-900 shadow-sm"
              >
                Chef's Special
              </Badge>
              <Badge
                v-if="item.isVegetarian"
                variant="default"
                class="absolute top-3 left-3 bg-green-600 text-white shadow-sm flex items-center"
              >
                <LeafIcon class="h-4 w-4 mr-1.5" /> Vegetarian
              </Badge>
            </div>
            <div class="p-6 flex flex-col flex-grow">
              <h3 class="text-2xl font-semibold text-green-800 mb-2 font-heading">{{ item.name }}</h3>
              <p class="text-gray-600 text-sm mb-4 leading-relaxed flex-grow">{{ item.description }}</p>
              <div class="flex justify-between items-center mb-4">
                <span class="text-2xl font-bold text-yellow-600">${{ item.price.toFixed(2) }}</span>
                <Badge
                  :variant="item.spiceLevel === 'Hot' ? 'destructive' : (item.spiceLevel === 'Medium' ? 'secondary' : 'default')"
                  class="text-xs font-medium"
                  :class="{
                    'bg-red-100 text-red-700 border-transparent': item.spiceLevel === 'Hot',
                    'bg-yellow-100 text-yellow-700 border-transparent': item.spiceLevel === 'Medium',
                    'bg-green-100 text-green-700 border-transparent': item.spiceLevel === 'Mild',
                  }"
                >
                  {{ item.spiceLevel }}
                </Badge>
              </div>
              <Button
                @click="handleOrder(item)"
                variant="default"
                class="w-full bg-green-700 hover:bg-green-800 text-white"
              >
                <ShoppingCartIcon class="h-5 w-5 mr-2" />
                Add to Order
              </Button>
            </div>
          </div>
        </div>

        <div v-if="filteredItems.length === 0" class="text-center py-12">
          <SearchXIcon class="h-16 w-16 text-gray-400 mx-auto mb-4" />
          <p class="text-xl text-gray-500">No dishes found for "{{ activeCategoryName }}".</p>
          <p class="text-gray-400 mt-2">Try selecting another category or checking back later!</p>
        </div>
      </div>
    </section>

    <!-- Dietary Information Section -->
    <section class="py-16 md:py-24 bg-green-50">
      <div class="container mx-auto px-4 sm:px-6 lg:px-8">
        <h2 class="font-heading text-3xl md:text-4xl font-semibold text-green-800 text-center mb-10">
          Dietary Options & Information
        </h2>
        <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div class="bg-white p-6 rounded-lg shadow-md flex items-start">
            <LeafIcon class="h-8 w-8 text-green-600 mr-4 mt-1 flex-shrink-0" />
            <div>
              <h3 class="text-xl font-semibold text-green-700 mb-2">Vegetarian & Vegan</h3>
              <p class="text-gray-600 text-sm leading-relaxed">
                We offer a wide array of delicious vegetarian and vegan dishes, clearly marked on our menu. Our Beyaynetu (vegetarian platter) is a house favorite!
              </p>
            </div>
          </div>
          <div class="bg-white p-6 rounded-lg shadow-md flex items-start">
            <WheatOffIcon class="h-8 w-8 text-yellow-600 mr-4 mt-1 flex-shrink-0" />
            <div>
              <h3 class="text-xl font-semibold text-green-700 mb-2">Gluten-Free Options</h3>
              <p class="text-gray-600 text-sm leading-relaxed">
                Most of our wots (stews) are naturally gluten-free. While traditional injera is made with teff flour, please inform your server about any gluten sensitivities for guidance.
              </p>
            </div>
          </div>
          <div class="bg-white p-6 rounded-lg shadow-md flex items-start">
            <InfoIcon class="h-8 w-8 text-blue-600 mr-4 mt-1 flex-shrink-0" />
            <div>
              <h3 class="text-xl font-semibold text-green-700 mb-2">Allergen Awareness</h3>
              <p class="text-gray-600 text-sm leading-relaxed">
                Your safety is important. Please speak to our staff about any allergies or dietary restrictions you may have. We'll do our best to accommodate your needs.
              </p>
            </div>
          </div>
        </div>
         <p class="text-center mt-10 text-gray-700">
          For detailed ingredient lists or specific concerns, please don't hesitate to <router-link to="/contact" class="text-green-700 hover:text-yellow-600 font-medium underline">contact us</router-link>.
        </p>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { menuData, MenuCategory, MenuItem } from '@/data/menuData'; // Assuming path is correct
import { LeafIcon, ShoppingCartIcon, SearchXIcon, WheatOffIcon, InfoIcon } from 'lucide-vue-next';
import Button from '@/components/ui/Button.vue';
import Badge from '@/components/ui/Badge.vue';
import { useToast } from '@/composables/useToast';

const activeCategory = ref<string>('all'); // 'all' or category id
const { toast } = useToast();

const uniqueCategories = computed(() => {
  const categories = new Map<string, MenuCategory>();
  menuData.forEach(item => {
    if (!categories.has(item.category.id)) {
      categories.set(item.category.id, item.category);
    }
  });
  return Array.from(categories.values());
});

const setActiveCategory = (categoryId: string) => {
  activeCategory.value = categoryId;
};

const filteredItems = computed(() => {
  if (activeCategory.value === 'all') {
    return menuData;
  }
  return menuData.filter(item => item.category.id === activeCategory.value);
});

const activeCategoryName = computed(() => {
  if (activeCategory.value === 'all') return 'All Dishes';
  const foundCategory = uniqueCategories.value.find(cat => cat.id === activeCategory.value);
  return foundCategory ? foundCategory.name : '';
});

const handleOrder = (item: MenuItem) => {
  // In a real app, this would likely add to a cart (e.g., using Pinia store)
  console.log('Ordering item:', item.name);
  toast({
    title: "Added to Order!",
    description: `${item.name} has been added to your (simulated) order.`,
    // variant: 'default' // or 'success' if you map it in useToast
  });
};

// SEO meta data would be handled via router or a dedicated Vue meta plugin.
</script>

<style scoped>
.font-heading {
  font-family: 'Nyala', serif; /* Ensure this font is configured */
}
/* Additional specific styles if needed */
</style>
